; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{C24115D1-7BDA-4D70-9679-4607C132D600}
AppName=Covid19Tab
AppVersion=alfa
;AppVerName=Covid19Tab alfa
AppPublisher=CSIS Software
AppPublisherURL=https://github.com/csisgo/Covid19Tab
AppSupportURL=https://github.com/csisgo/Covid19Tab
AppUpdatesURL=https://github.com/csisgo/Covid19Tab
DefaultDirName=c:\Covid19Tab
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=C:\Covid19Tab
OutputBaseFilename=mysetup
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"

[Dirs]
Name: "{app}\BaseDBF"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Covid19Tab\Covid19Tab.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Covid19Tab\BaseDBF\*"; DestDir: "{app}\BaseDBF"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Covid19Tab\Covid19Tab.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Covid19Tab\del_line.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Covid19Tab\sed.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Covid19Tab\transfer2.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Covid19Tab\verify.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Covid19Tab\libiconv2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Covid19Tab\libintl3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Covid19Tab\regex2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Covid19Tab\logo.bmp"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Covid19Tab\heading_model.c19"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Covid19Tab\settings.c19"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\Covid19Tab"; Filename: "{app}\Covid19Tab.exe"
Name: "{autodesktop}\Covid19Tab"; Filename: "{app}\Covid19Tab.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\Covid19Tab.exe"; Description: "{cm:LaunchProgram,Covid19Tab}"; Flags: nowait postinstall skipifsilent

